# =============================================================================
# OXOCARBON FUZZEL CONFIG
# =============================================================================

font=JetBrains Mono:size=11
terminal=kitty
prompt="❯   "
layer=overlay

[colors]
# Фон меню (base00) и текст (base04)
background=161616ff
text=dde1e6ff

# Цвет поисковой строки при выделении
match=ff7eb6ff
selection-match=ff7eb6ff

# Строка выбранного элемента (фон base02, текст base04)
selection=393939ff
selection-text=dde1e6ff

# Рамка самого окна меню (светло-розовый base0C)
border=ff7eb6ff

[border]
width=2
radius=8

[dmenu]
exit-immediately-if-empty=yes
